name: flutter_template
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  another_flushbar: ^1.12.30
  auto_route: ^7.8.3
  crypto: ^3.0.3
  dio: ^5.3.3
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localization: ^0.1.14
  flutter_native_splash: ^2.3.2
  flutter_svg: ^2.0.7
  logger: ^1.2.0
  permission_handler: ^11.0.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
